-- :DATABASE_AUTHENTICATOR_PASSWORD is actually not a variable replaced by
-- graphile migrate, this is mainly for CI setup.
CREATE ROLE :DATABASE_AUTHENTICATOR WITH LOGIN PASSWORD ':DATABASE_AUTHENTICATOR_PASSWORD' NOINHERIT;
CREATE ROLE :DATABASE_VISITOR;
CREATE ROLE :DATABASE_ADMIN WITH nologin;
