name: Docs

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --immutable
        working-directory: ./docs

      - name: Build Docs
        run: bun run build
        working-directory: ./docs

      # actions/upload-artifact@v4 has error:
      # https://github.com/actions/deploy-pages/issues/389
      - uses: actions/upload-pages-artifact@v3
        # Only on main push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: github-pages
          path: ./docs/dist/

  deploy:
    name: Deploy Docs
    needs: build
    # Only on pushes to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
